### PR TITLE
Ttf driver skew does not work properly after paste inside

### LINKED ISSUE #963: TTF driver: skew does not work properly after paste inside
Image

### PR DESCRIPTION
**Pull request by jirkakunze**
- calculation of the transformation matrix for Gen_In_Region corrected
- minor optimizations

fixes #963

### CODE REVIEW

File: Driver/Font/TrueType/Adapter/ttwidths.c [hunk 1]
```diff
@@ -678,33 +678,33 @@ EC(     ECCheckBounds( (void*)fontBuf ) );
                                               WBFIXED_TO_WWFIXEDASDWORD( fontBuf->FB_heightAdjust );
 
 
-                styleMatrix.xx = TrueType_GrMulWWFixed( styleMatrix.xx, SCRIPT_FACTOR );
```
Comment (bluewaysw) [inline Driver/Font/TrueType/Adapter/ttwidths.c:681]: What is the reason not to use the "local" TrueType version of GrMulWWFixed?

Comment (jirkakunze) [reply Driver/Font/TrueType/Adapter/ttwidths.c:681]: In ttadapter.h #451, GrMulWWFixed() is overwritten with TrueType_GrMulWWFixed(). The precompiler then replaces all GrMulWWFixed calls with TrueType_GrMulWWFixed. I have standardized the calls in the code.

Comment (bluewaysw) [reply Driver/Font/TrueType/Adapter/ttwidths.c:681]: Ok, I've got it. Thx! :-)
